In [4]:
import numpy as np
import pandas as pd

In [8]:
path = '/home/warrior/Documents/computing/isl_book/datasets/auto.csv'

In [9]:
auto = pd.read_csv(path)
auto.shape

(397, 9)

In [24]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64  
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object 
 4   weight        397 non-null    int64  
 5   acceleration  397 non-null    float64
 6   year          397 non-null    int64  
 7   origin        397 non-null    int64  
 8   name          397 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.0+ KB


In [15]:
auto.head(3)

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite

In [27]:
print(auto.shape)
auto = auto[auto['horsepower'] != '?']
print(auto.shape)

(397, 9)
(392, 9)


In [88]:
auto['horsepower'] = auto['horsepower'].astype(int)

<ipython-input-88-c179eff361a6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto['horsepower'] = auto['horsepower'].astype(int)


In [89]:
X1, X2 = auto[['displacement','horsepower','weight']].values, auto[['acceleration','mpg']].values
n, d1, d2 = X1.shape[0], X1.shape[1], X2.shape[1]
print(f'n: {n}')
print(f'd1: {d1}')
print(f'd2: {d2}')

n: 392
d1: 3
d2: 2


In [90]:
S1 = np.cov(X1.T)
S2 = np.cov(X2.T)
S1.shape, S2.shape

((3, 3), (2, 2))

In [91]:
S1

array([[ 10950.36755409,   3614.03374393,  82929.10013897],
       [  3614.03374393,   1481.56939297,  28265.6202307 ],
       [ 82929.10013897,  28265.6202307 , 721484.70900752]])

In [92]:
S2

array([[ 7.61133123,  9.11551438],
       [ 9.11551438, 60.91814187]])

In [122]:
X = np.hstack([X1,X2]).T
print(X.shape)
S = np.cov(X)
S.shape

(5, 392)


(5, 5)

In [129]:
#S1
S1 = S[:d1,:d1]
print(S1)

[[ 10950.36755409   3614.03374393  82929.10013897]
 [  3614.03374393   1481.56939297  28265.6202307 ]
 [ 82929.10013897  28265.6202307  721484.70900752]]


In [130]:
#S2
S2 = S[d1:,d1:]
print(S2)

[[ 7.61133123  9.11551438]
 [ 9.11551438 60.91814187]]


In [131]:
#S12
S12 = S[:d1,d1:]
print(S12)

[[ -156.99443538  -657.58520669]
 [  -73.18696696  -233.85792578]
 [ -976.81525262 -5517.44070411]]


In [132]:
#S12 T
S12t = S[d1:,:d1]
print(S12t)

[[ -156.99443538   -73.18696696  -976.81525262]
 [ -657.58520669  -233.85792578 -5517.44070411]]


In [205]:
C = np.power(S1,-1/2) @ S12 @ np.power(S2,-1/2)
C

array([[-11.93028245,  -5.7819269 ],
       [-20.24676771,  -9.80371475],
       [ -4.14073367,  -2.00867664]])

In [195]:
print(np.sqrt(S1))
print('')
print(1/np.sqrt(S1))

[[104.64400391  60.11683411 287.97413102]
 [ 60.11683411  38.49115993 168.1238241 ]
 [287.97413102 168.1238241  849.40256004]]

[[0.00955621 0.01663428 0.00347253]
 [0.01663428 0.02597999 0.005948  ]
 [0.00347253 0.005948   0.0011773 ]]


In [197]:
print(np.sqrt(S2))
print('')
print(1/np.sqrt(S2))

[[2.75886412 3.01919101]
 [3.01919101 7.80500749]]

[[0.36246801 0.33121455]
 [0.33121455 0.12812288]]


In [212]:
C = (1/np.sqrt(S1)) @ S12 @ (1/np.sqrt(S2))
C

array([[-11.93028245,  -5.7819269 ],
       [-20.24676771,  -9.80371475],
       [ -4.14073367,  -2.00867664]])

In [202]:
print(np.corrcoef(X).shape)
np.corrcoef(X)

(5, 5)


array([[ 1.        ,  0.897257  ,  0.9329944 , -0.5438005 , -0.80512695],
       [ 0.897257  ,  1.        ,  0.86453774, -0.68919551, -0.77842678],
       [ 0.9329944 ,  0.86453774,  1.        , -0.4168392 , -0.83224421],
       [-0.5438005 , -0.68919551, -0.4168392 ,  1.        ,  0.42332854],
       [-0.80512695, -0.77842678, -0.83224421,  0.42332854,  1.        ]])

In [213]:
np.corrcoef(X)[:3,3:]

array([[-0.5438005 , -0.80512695],
       [-0.68919551, -0.77842678],
       [-0.4168392 , -0.83224421]])

In [177]:
S12

array([[ -156.99443538,  -657.58520669],
       [  -73.18696696,  -233.85792578],
       [ -976.81525262, -5517.44070411]])

In [178]:
np.power(S1,-1/2) @ S12

array([[ -6.10970818, -29.33358027],
       [-10.32297969, -49.83180129],
       [ -2.13048711, -10.17014564]])

In [198]:
S12 @ np.power(S2,-1/2)

array([[ -274.70725113,  -136.25054899],
       [ -103.9850828 ,   -54.20313833],
       [-2181.52093788, -1030.44579322]])

In [149]:
np.var(X[0],ddof=True)

10950.367554086853

In [182]:
S12

array([[ -156.99443538,  -657.58520669],
       [  -73.18696696,  -233.85792578],
       [ -976.81525262, -5517.44070411]])

In [187]:
S12[0][0] # (X1_i, X2_i)

-156.99443538284882

In [188]:
np.sqrt(np.var(X[0],ddof=True)), np.sqrt(np.var(X[3],ddof=True))

(104.64400390890466, 2.758864119188082)

In [189]:
print(np.std(X[0], ddof=True), np.std(X[3], ddof=True))
print('')
print(1/np.std(X[0], ddof=True), 1/np.std(X[3], ddof=True))
print('')
print(1/np.std(X[0], ddof=True) * 1/np.std(X[3], ddof=True))
print('')
print('p',-156.99443538 / (np.std(X[0], ddof=True)*np.std(X[3], ddof=True)))

104.64400390890466 2.758864119188082

0.009556209268048708 0.36246801466043

0.003463820201069216

p -0.5451912908339701


In [200]:
print(np.std(X[0], ddof=True), np.std(X[3], ddof=True))
print('')
print(1/np.std(X[0], ddof=True), 1/np.std(X[3], ddof=True))
print('')
print(1/np.std(X[0], ddof=True) * 1/np.std(X[3], ddof=True))
print('')
print('p',-156.99443538 / (np.std(X[0])*np.std(X[3])))

104.64400390890466 2.758864119188082

0.009556209268048708 0.36246801466043

0.003463820201069216

p -0.5451912908339701


In [147]:
3614.03374393 / (np.std(X[0], ddof=True)*np.std(X[1], ddof=True))

0.8972570018428841

In [152]:
-156.99443538 / (np.std(X[0], ddof=True)*np.std(X[3], ddof=True))

-0.5438004967246997